secultce/aurora-ui

- site/layouts/partials/docs-navbar.html
- site/static/docs/5.3/css/custom.css
- site/static/docs/5.3/examples/collapse-accordion.html
- site/static/docs/components.html
> Create component for Permission Accordion

- site/static/docs/5.3/css/custom.css
- site/static/docs/5.3/examples/intro-cards.html
- site/static/docs/components.html
Add the component intro card
Resolve #6
> Add new component intro cards

- .github/PULL_REQUEST_TEMPLATE.md
Inclui um modelo padrão de pull request personalizado para o nosso projeto de desenvolvimento.
---
fix #13 
---
incluir o arquivo `.github/pull_request_template.md` 
---
Marque as opções relevantes:
---
---
**Checklist: ✔️**
---
**Observação:**
> Implements pull request template.

- dist/css/bootstrap.css
- site/static/docs/5.3/css/custom.css
- site/static/docs/5.3/examples/sidebar.html
- site/static/docs/components.html
| Branch?       | feature/crate-sidebar-component                                                |
| Bug fix?      |no                                                                                                                    |
| Deprecations? | yes                                                   |
| Issues        | Fix #5  |
> Adds sidebar component.

- site/static/docs/5.3/examples/cards.html
- site/static/docs/5.3/examples/collapse-accordion.html
- site/static/docs/5.3/examples/draft-card.html
- site/static/docs/5.3/examples/footer.html
- site/static/docs/5.3/examples/intro-cards.html
- site/static/docs/5.3/examples/navbar.html
- site/static/docs/5.3/examples/sidebar.html
- site/static/docs/5.3/examples/updated-card.html
| Branch?       |improv/refactor-link-custon.css                                                |
| Deprecations? |no                                                   |
| Issues        | Fix #27   |
> Adds the updated custom.css file link to each component's document.

- dist/css/custom.css
- site/static/docs/5.3/examples/footer.html
| Branch?       | improv/font-size-classes                                                 |
| Issues        | Fix #33  |
> Improvements classes of font size.

- dist/css/custom.css
- site/static/docs/5.3/examples/navbar.html
- site/static/docs/5.3/examples/tabs.html
- site/static/docs/components.html
| Branch?       | feature/create-tabs-component                                                 |
| Deprecations? |no                                                   |
| Issues        | Fix #26   |
> Adds tabs component.

- dist/css/bootstrap.css
| Branch?       |improv/colors-classes                                                 |
| Issues        | Fix #...  |
> adds new colors in bootstrap classes

- dist/css/custom.css
- site/static/docs/5.3/examples/dashboard.html
- site/static/docs/components.html
| Branch?       | feat/dashboard-card                                                 |
| Issues        | Fix #37   |
- Como está:
> Create Dashboard Card. 

- dist/css/custom.css
- site/static/docs/5.3/examples/timeline.html
- site/static/docs/components.html
| Branch?       | feat/create-timeline                                            |
| Deprecations? | yes                                                  |
| Issues        | Fix #41 |
> Create Component Timeline .

- dist/css/custom.css
- site/static/docs/5.3/examples/search-input.html
- site/static/docs/components.html
| Branch?       | feat/create-search-input                                       |
| Issues        | Fix #50  |
> Create Input Search

- package.js
- package.json
- site/content/docs/5.3/examples/sidebars/index.html
- site/layouts/partials/docs-navbar.html
- site/layouts/partials/footer.html
- site/static/docs/5.3/examples/agent-card.html
- site/static/docs/5.3/examples/cards.html
- site/static/docs/5.3/examples/collapse-accordion.html
- site/static/docs/5.3/examples/dashboard.html
- site/static/docs/5.3/examples/draft-card.html
- site/static/docs/5.3/examples/dropdown.html
- site/static/docs/5.3/examples/footer.html
- site/static/docs/5.3/examples/form-stepper.html
- site/static/docs/5.3/examples/intro-cards.html
- site/static/docs/5.3/examples/navbar.html
- site/static/docs/5.3/examples/search-input.html
- site/static/docs/5.3/examples/sidebar.html
- site/static/docs/5.3/examples/tabs.html
- site/static/docs/5.3/examples/timeline.html
- site/static/docs/5.3/examples/updated-card.html
- site/static/docs/5.3/examples/wysiwyg.html
- site/static/docs/components.html
| Branch?       | fix/lint-files                                               |
| Bug fix?      | yes                                                                                                                   |
| Issues        | Fix #57   |
> Adjust the files with lint rules

- dist/css/custom.css
- dist/css/side-filter.css
- dist/js/side-filter.js
- site/static/docs/5.3/examples/side-filter.html
- site/static/docs/components.html
| Branch?       | feature/side-filter                                              |
| Bug fix?      | no                                                                                                                 |
| New feature?  | yes                                                                |
| Deprecations? | no                                                  |
| Issues        | Fix #40  |
Este componente é inicialmente um botão que fica fixado no lado esquerdo da tela e, ao ser clicado, expande …
> Create Side Filter Component

- package.js
| Branch?       | hotfix/update-css-styles-in-package                                         |
| Bug fix?      | yes                                                                                                                    |
| New feature?  | no                                                |
| Deprecations? | no                                        |
| Issues        | https://github.com/orgs/secultce/projects/17/views/1?pane=issue&itemId=79277110 |
> Update package.js to include new CSS files for fixing layout issues

- dist/css/card.css
- site/static/docs/5.3/examples/card-question.html
- site/static/docs/components.html
| Branch?       | feat/create-card-question                                           |
| Issues        | Fix #54 |
> Create Card Question. 

- dist/css/card.css
- dist/css/colors.css
- package-lock.json
- package.js
- package.json
- site/static/docs/5.3/examples/agent-card.html
- site/static/docs/5.3/examples/draft-card.html
- site/static/docs/5.3/examples/dropdown.html
- site/static/docs/5.3/examples/opportunity-cards.html
- site/static/docs/5.3/examples/search-input.html
- site/static/docs/5.3/examples/tabs.html
- site/static/docs/5.3/examples/timeline.html
- site/static/docs/components.html
| Branch?       | feature/create-opportunity-card                                                |
| Issues        | Fix #61   |
> Create opportunity card

- dist/css/colors.css
- dist/css/custom.rtl.css
- dist/css/layout.css
| Branch?       |fix/update-variable-name               |
| Bug fix?      | no                                                                                                                |
| New feature?  |no                                                              |
| Deprecations? | no                                           |
| Issues        | Fix #73  |
> Rename CSS variable and update color

- dist/css/card.css
- hugo.yml
- package.js
- package.json
| Branch?       | fix/adjust-card-faq                                               |
| Bug fix?      | yes                                                                                                                    |
| Issues        | Fix #75  |
> Adjust Card FaQ question

- dist/css/colors.css
- dist/css/snackbar.css
- dist/js/snackbar.js
- hugo.yml
- package.js
- package.json
- site/static/docs/5.3/examples/snackbar.html
- site/static/docs/components.html
| Branch?       | feature/snackbar-component                                            |
| New feature?  | yes                                                                   |
| Deprecations? |no                                      |
| Issues        | Fix #25  |
> Create Snackbar component

- Dockerfile
- README.md
- docker-compose.yml
- package.json
| Branch?       |feature/add-docker-compose                                                 |
| Issues        | Fix #78   |
> Adds docker-compose file.

- dist/css/card.css
- site/static/docs/5.3/examples/draft-card.html
| Branch?       | improv/repair-draft-card                                            |
| Bug fix?      | yes                                                                                                                    |
| Issues        | Fix #81   |
> Repair Draft Card

- dist/css/layout.css
- hugo.yml
- package.js
- package.json
- site/static/docs/5.3/examples/sidebar.html
| Branch?       | improv/menu-sidebar                                               |
| Issues        | Fix #84  |
> Improvements on menu sidebar

- dist/css/filter-date.css
- site/static/docs/5.3/examples/filter-date.html
- site/static/docs/components.html
| Branch?       |                    feat/create-filter-date-filters                         |
| Issues        | Fix #51   |
> Create Filter Date.
